morebits: fix error handling on no connectivity
azatoth/twinkle pull request #1139
Opened 2020-09-27 10:24 UTC by siddharthvp

commit 1: fix error handling on no internet 
errorCode is `null` on no internet connectivity, not `undefined` let alone the string `'undefined'` which the code was looking for.
This bug was also preventing any onFailure handler from triggering because of the TypeError on line 3260 (null doesn't have `indexOf` method).

commit 2: wait for 2 seconds after a connection error
Retrying immediately after encountering a network error is pointless, the most likely outcome is that the same error would recur. (Ever since I added a 5-sec wait in SDZeroBot, it has never ever encountered failures due to lack of connectivity. 5 may be excessive for a user-facing script though.)

2020-09-28 01:07 UTC, Amorymeltzer commented on morebits.js
> +			// wait for sometime for client to regain connnectivity
I've no idea how to trigger this to test it!

2020-09-28 10:27 UTC, Amorymeltzer commented on morebits.js
> +			// wait for sometime for client to regain connnectivity
Ah, I was dumb, needed to have `load`ed the page.  All checks out!

2020-09-28 10:31 UTC, Amorymeltzer requested changes
>This bug was also preventing any onFailure handler from triggering because of the TypeError on line 3260 (null doesn't have indexOf method).

Commit 1 is actually insufficient to prevent this, as once we've exhausted replies, the `errorCode` enters the "hard error" section.  Might as well wrap `protectedpage`, `abusefilter`, and `spamblacklist` in an `if (errorCode) {` block, yeah?  Other than that, this all looks 👍

2020-09-28 11:46 UTC, siddharthvp commented
> Commit 1 is actually insufficient to prevent this, as once we've exhausted replies, the errorCode enters the "hard error" section. Might as well wrap protectedpage, abusefilter, and spamblacklist in an if (errorCode) { block, yeah? 

Oh yeah. Put it into a switch instead as that seems to makes the whole thing tidier.

2020-09-29 09:41 UTC, Amorymeltzer approved these changes

2020-09-29 09:41 UTC, Amorymeltzer commented
>Put it into a switch instead as that seems to makes the whole thing tidier.

Nice! LGTM 👍 

(linking #707 as the source of this)

2020-09-29 09:41 UTC, merged