xfd: Use a unified user notification function
azatoth/twinkle pull request #1153
Opened 2020-10-11 21:09 UTC by Amorymeltzer

With all the XfD notices unified (29ae3373), we don't need to handle them individually.  This handles all current notifications, including without double-logging on MfDs, TfMs, and RfD, and handles non-userspace targets in RfD target notifications; the majority of the complexity is due to handling MfD and RfD.  Should also work for #1001.

Also fixes a bug in MfD notifications, where you could only notify the userspace owner if you were also notifying the creator, regardless of whether they were the same or not.

----

I think this is a benefit, as despite the annoying handlings, it's all in one spot rather than disparate.

2020-10-12 08:17 UTC, siddharthvp requested changes

2020-10-12 08:17 UTC, siddharthvp commented on modules/twinklexfd.js
> +		notifytext += '|1=' + (params.venue === 'tfd' ? mw.config.get('wgTitle') : Morebits.pageNameNorm) + '}} ~~~~';
```suggestion
		notifytext += '|1=' + Morebits.pageNameNorm + '}} ~~~~';
```
I have fixed {{Tfd notice}} so that we don't need the special case.

2020-10-12 08:17 UTC, siddharthvp commented on modules/twinklexfd.js
> +				}
```suggestion

```
Unnecessary per [changes made](https://en.wikipedia.org/w/index.php?title=Template:Tfd_notice&diff=983106167&oldid=954464172&diffmode=source) to Template:Tfd notice.

2020-10-13 00:52 UTC, Amorymeltzer commented
Nice, thanks @siddharthvp!

2020-11-11 11:50 UTC, merged