tag: Add an input for redirect page name for R avoided double redirect
azatoth/twinkle pull request #1164
Opened 2020-10-19 17:29 UTC by TheTVExpert

Added an input to allow the user to enter the redirect page name for the R avoided double redirect template.

2020-10-20 01:02 UTC, Amorymeltzer requested changes
Needs a quick bug fix, but otherwise nice PR @TheTVExpert!

2020-10-20 01:02 UTC, Amorymeltzer commented on modules/friendlytag.js
>  			}
This is an indent too deep; right now it's under `(tagName === 'R from alternative language')`, which obviously won't work!

What should happen is something like:

```suggestion
				if (params.altLangTo) {
					tagText += '|to=' + params.altLangTo;
				}
			} else if (tagName === 'R avoided double redirect' && params.doubleRedirectTarget) {
				tagText += '|1=' + params.doubleRedirectTarget;
			}
```

2020-10-20 14:48 UTC, TheTVExpert commented
Fixed.

2020-10-24 17:48 UTC, Amorymeltzer approved these changes
Looks great, nice addition!  I wonder how many others there are that might benefit from this kind of thing?

2020-10-24 17:50 UTC, Amorymeltzer commented
Merged as 2c31888

2020-10-24 17:50 UTC, closed without merging